# Generated by Django 5.0.6 on 2024-07-11 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_order_status_alter_order_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='cart_count',
            field=models.IntegerField(default=0),
        ),
    ]
