# Generated by Django 5.0.6 on 2024-07-23 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_product_image_product_banner_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='banner',
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='products'),
        ),
    ]
