# Generated by Django 5.0.6 on 2024-12-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_userinformation_reset_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='abc', unique=True, verbose_name='slug'),
            preserve_default=False,
        ),
    ]
