# Generated by Django 5.0.6 on 2025-01-08 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_category_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='city',
            new_name='commune',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='country',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='apartment',
            new_name='extra_description',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='state',
            new_name='province',
        ),
        migrations.RemoveField(
            model_name='address',
            name='default',
        ),
        migrations.RemoveField(
            model_name='address',
            name='street',
        ),
        migrations.RemoveField(
            model_name='address',
            name='zip_code',
        ),
    ]
